-- Seed batches now run sequentially from `supabase/seeds/`.
-- Order:
--   1. `supabase/seeds/00_helpers.sql`
--   2. `supabase/seeds/01_auth.sql`
--   3. `supabase/seeds/02_domain_data.sql`
--
-- `supabase/config.toml` points `db.seed.sql_paths` at those files, so
-- `supabase db reset` still works without manual changes.
